development:
  adapter: mysql
  database: yubnub_development
  host: localhost
  username: root
  password:

test:
  adapter: mysql
  database: yubnub_test
  host: localhost
  username: root
  password:

production:
  adapter: mysql
  database: yubnub
  host: localhost
  username: jon_aquino
  password:

